#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define COCOS2D_DEBUG 1

#define DISPLAY_TIME_LOADING_SCENE 2
#define TRANSITION_TIME 0.5
#define GAME_OVER_TRANSITION_TIME 0.2

#endif // __DEFINITIONS_H__